# Generated by Django 2.2.6 on 2019-10-24 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userInfo',
        ),
    ]
